add gtk tag, sort some sections by alphabet, add gnome tag for core circle apps
myfreeweb/awesome-gtk pull request #230
Opened 2024-09-21 20:26 UTC by Drsheppard01

2024-09-21 21:07 UTC, loicreynier commented
Thank you for this huge (tedious) work! The linter detected a few errors, could you correct them? I'll try to take a look at it in the coming days before merging.

2024-09-23 08:51 UTC, loicreynier approved these changes

2024-09-23 09:01 UTC, loicreynier commented
Closes #226, closes #227.

2024-09-23 09:02 UTC, loicreynier commented
@Drsheppard01 if you agree with my changes, we can merge it.

2024-09-23 10:04 UTC, Drsheppard01 commented
I make some changes, now it looks better

2024-09-23 12:35 UTC, loicreynier requested changes

2024-09-23 12:35 UTC, loicreynier commented on README.md
> +- [NewsFlash](https://apps.gnome.org/NewsFlash/) - News reader designed to complement an already existing web-based RSS reader account `#rust` `#gtk4` `#libadwaita` `#gnome`.
```suggestion
- [NewsFlash](https://apps.gnome.org/NewsFlash) - News reader designed to complement an already existing web-based RSS reader account `#rust` `#gtk4` `#libadwaita` `#gnome`.
```

2024-09-23 12:35 UTC, loicreynier commented on README.md
> +- [Solanum](https://apps.gnome.org/Solanum/) - Pomodoro timer for the GNOME desktop `#rust` `#gtk4` `#libadwaita` `#gnome`.
```suggestion
- [Solanum](https://apps.gnome.org/Solanum) - Pomodoro timer for the GNOME desktop `#rust` `#gtk4` `#libadwaita` `#gnome`.
```

2024-09-23 12:35 UTC, loicreynier commented on README.md
> +- [Wildcard](https://gitlab.gnome.org/World/Wildcard) - Regex tester `#rust` `#gtk4` `#libadwaita` `#gnome`.
```suggestion
- [Wildcard](https://gitlab.gnome.org/World/Wildcard) - Regex tester `#rust` `#gtk4` `#libadwaita`.
```

Projects from `gitlab.gnome.org/World` are not part of the core GNOME applications.

2024-09-23 12:54 UTC, Drsheppard01 commented
In continuation with the `#gnome` tag, would it be correct to also remove it for gedit and morphosis, because, they are also not gnome core apps, I also put the gnome tag next to the gnome circle apps, but not for gnome incubator apps

2024-09-23 13:03 UTC, loicreynier commented
Yes indeed we should definitely remove the `#gnome` tag for Gedit and Morphosis, as they are neither part of the core apps nor part of GNOME Circle.

2024-09-23 16:40 UTC, loicreynier commented
Closes #220.

2024-09-23 16:41 UTC, merged

2024-09-23 16:41 UTC, loicreynier commented
Thanks @Drsheppard01, now merged.