Add Pinta
myfreeweb/awesome-gtk pull request #242
Opened 2024-10-31 20:47 UTC by GerryT11

Pinta is a free, open source program for drawing and image editing. CSharp/C# GTK3

https://github.com/PintaProject/Pinta/tree/master
https://www.pinta-project.com/

Pinta 2.1 is currently still on GTK3, but the upcoming version 2.2 will be based on GTK4 and libadwaita.

2024-10-31 20:50 UTC, GerryT11 commented
Oh, there was a typo in my pull request: I wanted to type #gkt3 instead of #gtk2. That was a mistake. Could you please correct it? The current Pinta 2.1 uses GTK3.

2024-11-01 12:03 UTC, loicreynier requested changes

2024-11-01 12:03 UTC, loicreynier commented on README.md
> +- [Pinta](https://www.pinta-project.com/) - Drawing and image editing program. `#c#` `#gtk2`.
```suggestion
- [Pinta](https://www.pinta-project.com) - Drawing and image editing program with simple interface and layered organization `#c#` `#gtk3`.
```

2024-11-01 23:06 UTC, loicreynier approved these changes

2024-11-01 23:06 UTC, merged