Update README.md
myfreeweb/awesome-gtk pull request #84
Opened 2023-08-03 04:45 UTC by phase1geo

Includes the following projects:

- Outliner
- TextShine
- Actioneer
- Annotator
- Journaler

2023-08-05 07:40 UTC, loicreynier requested changes
LGTM. I made some slight rephrasing to better align with the usual style employed here.

2023-08-05 07:40 UTC, loicreynier commented on README.md
> +- [Annotator](https://github.com/phase1geo/annotator) - Communicate with images. Better. `#vala` `#granite`.
```suggestion
- [Annotator](https://github.com/phase1geo/annotator) - Image annotation application designed for elementary OS `#vala` `#granite`.
```

2023-08-05 07:40 UTC, loicreynier commented on README.md
> +- [Actioneer](https://github.com/phase1geo/actioneer) - Automate actions on file changes `#vala` `#granite`.
```suggestion
- [Actioneer](https://github.com/phase1geo/actioneer) - Tool to automate actions on file changes `#vala` `#granite`.
```

2023-08-06 01:13 UTC, phase1geo commented on README.md
> +- [Actioneer](https://github.com/phase1geo/actioneer) - Automate actions on file changes `#vala` `#granite`.
I am good with these changes.

2023-08-06 07:23 UTC, loicreynier approved these changes

2023-08-06 07:28 UTC, merged