Add Weather
myfreeweb/awesome-gtk pull request #93
Opened 2023-08-31 10:47 UTC by Kimiblock

2023-08-31 19:29 UTC, loicreynier requested changes

2023-08-31 19:29 UTC, loicreynier commented on README.md
> +- [Weather](https://github.com/amit9838/weather) - Beautiful and lightweight weather app build using Gtk4, `#libadwaita` and `#python`.
```suggestion
- [Weather](https://github.com/amit9838/weather) - Lightweight weather application with dynamically changing gradient-based background according to current weather condition `#python` `#libadwaita`.
```

"Beautiful" is not objective, I suggest rather highlighting the background feature. Also the tags should be "`#python` `#libadwaita`" to fit the style used here.

2023-09-01 08:12 UTC, Kimiblock commented
Thanks for your advice!I’ll update when I’m back home.Sent from my iPhoneOn Sep 1, 2023, at 3:29 AM, Loïc Reynier ***@***.***> wrote:﻿
@loicreynier requested changes on this pull request.



In README.md:
> @@ -784,3 +784,4 @@ Clients for commercial social platforms that had their API access cut off in a w
 - [GNOME Weather](https://wiki.gnome.org/Apps/Weather) - Weather application for the GNOME desktop `#gjs` `#gnome`.
 - [Nimbus](https://github.com/danrabbit/nimbus) - Minimal weather applet  `#vala` `#libhandy`.
 - [Meteo](https://gitlab.com/bitseater/meteo) - Forecast application using OpenWeatherMap API `#vala`.
+- [Weather](https://github.com/amit9838/weather) - Beautiful and lightweight weather app build using Gtk4, `#libadwaita` and `#python`.

⬇️ Suggested change
-- [Weather](https://github.com/amit9838/weather) - Beautiful and lightweight weather app build using Gtk4, `#libadwaita` and `#python`.
+- [Weather](https://github.com/amit9838/weather) - Lightweight weather application with dynamically changing gradient-based background according to current weather condition `#python` `#libadwaita`.


"Beautiful" is not objective, I suggest rather highlighting the background feature. Also the tags should be "#python #libadwaita" to fit the style used here.

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

2023-09-02 09:59 UTC, loicreynier approved these changes

2023-09-02 10:01 UTC, merged